import json

notebook_content = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# 🚀 Mini-Proyecto Python: Sistema de Gestión TechStore\n",
    "\n",
    "¡Bienvenido a tu cuaderno de introducción y consolidación de Python!\n",
    "\n",
    "Este proyecto integra todos los conceptos fundamentales exigidos en tu curso:\n",
    "1. **Módulos**: Importación de módulos del sistema y nuestro módulo propio `modulo_inventario.py`.\n",
    "2. **Listas y Diccionarios**: Estructuras de datos para almacenar y manipular colecciones.\n",
    "3. **Funciones**: Definición de funciones con y sin parámetros.\n",
    "4. **Encapsulamiento**: Protección de datos mediante atributos privados (`__atributo`) y `@property`.\n",
    "5. **Herencia**: Creación de clases derivadas (`ProductoElectronico`, `ProductoAlimento`).\n",
    "6. **Polimorfismo**: Sobrescritura de métodos para respuestas específicas según la clase.\n",
    "7. **Manejo de Excepciones**: Captura de errores con `try / except / else / finally` y excepciones personalizadas.\n",
    "\n",
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 📦 MÓDULO 1: Importación de Módulos (Estándar y Personalizado)\n",
    "\n",
    "En Python, los **módulos** son archivos `.py` que contienen código reutilizable. Usaremos módulos nativos de Python (`datetime`, `math`, `json`) y nuestro archivo local **`modulo_inventario.py`**."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Importación de módulos estándar de Python\n",
    "import datetime\n",
    "import math\n",
    "import json\n",
    "\n",
    "# 2. Importación de nuestro módulo personalizado 'modulo_inventario'\n",
    "import modulo_inventario as mi\n",
    "from modulo_inventario import formatear_moneda, generar_codigo_unico\n",
    "\n",
    "# Probar funciones del módulo personalizado\n",
    "fecha_actual = mi.obtener_timestamp()\n",
    "codigo_demo = generar_codigo_unico(prefijo='TECH')\n",
    "precio_demo = formatear_moneda(1250.75)\n",
    "\n",
    "print(f'📅 Fecha y Hora de Inicio: {fecha_actual}')\n",
    "print(f'🏷️ Código Generado: {codigo_demo}')\n",
    "print(f'💰 Precio Formateado: {precio_demo}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 🛠️ MÓDULO 2: Funciones (Con y Sin Parámetros)\n",
    "\n",
    "Las funciones nos permiten dividir el código en bloques lógicos y reutilizables."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# A) FUNCIÓN SIN PARÁMETROS: Imprime la portada del sistema\n",
    "def mostrar_banner():\n",
    "    print('=' * 60)\n",
    "    print('       🏬 SISTEMA DE GESTIÓN DE INVENTARIO - TECHSTORE')\n",
    "    print('=' * 60)\n",
    "\n",
    "# B) FUNCIÓN CON PARÁMETROS: Calcula el precio con descuento opcional (parámetro por defecto)\n",
    "def calcular_descuento(precio_base, porcentaje_descuento=10):\n",
    "    \"\"\"\n",
    "    Recibe el precio base y aplica un porcentaje de descuento.\n",
    "    Si no se pasa el porcentaje, aplica el 10% por defecto.\n",
    "    \"\"\"\n",
    "    descuento = precio_base * (porcentaje_descuento / 100)\n",
    "    precio_final = precio_base - descuento\n",
    "    return precio_final, descuento\n",
    "\n",
    "# Probar las funciones\n",
    "mostrar_banner()\n",
    "precio_original = 500.0\n",
    "precio_con_desc, monto_desc = calcular_descuento(precio_original, porcentaje_descuento=15)\n",
    "print(f'Precio original: {formatear_moneda(precio_original)}')\n",
    "print(f'Descuento (15%): -{formatear_moneda(monto_desc)}')\n",
    "print(f'Precio a pagar: {formatear_moneda(precio_con_desc)}')\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 📋 MÓDULO 3: Listas y Diccionarios\n",
    "\n",
    "- **Listas**: Secuencias ordenadas y mutables de elementos.\n",
    "- **Diccionarios**: Estructuras clave-valor para representar datos estructurados."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Lista de categorías disponibles\n",
    "categorias = ['Electrónica', 'Computación', 'Alimentos', 'Accesorios']\n",
    "\n",
    "# Agregar un elemento a la lista\n",
    "categorias.append('Audio y Video')\n",
    "\n",
    "# 2. Diccionario de configuración de la tienda\n",
    "tienda_info = {\n",
    "    'nombre': 'TechStore Central',\n",
    "    'sucursal': 'San José',\n",
    "    'abierto': True,\n",
    "    'impuesto_local': 0.13\n",
    "}\n",
    "\n",
    "# 3. Lista de Diccionarios (Simulación de catálogo de productos)\n",
    "catalogo_datos = [\n",
    "    {'id': 1, 'nombre': 'Laptop Gamer', 'precio': 1200.0, 'stock': 5, 'categoria': 'Computación'},\n",
    "    {'id': 2, 'nombre': 'Audífonos Bluetooth', 'precio': 80.0, 'stock': 15, 'categoria': 'Audio y Video'},\n",
    "    {'id': 3, 'nombre': 'Bebida Energética', 'precio': 3.50, 'stock': 50, 'categoria': 'Alimentos'}\n",
    "]\n",
    "\n",
    "print(f\"📌 Tienda: {tienda_info['nombre']} - Sucursal: {tienda_info['sucursal']}\")\n",
    "print(f\"📁 Categorías registradas ({len(categorias)}): {', '.join(categorias)}\\n\")\n",
    "\n",
    "print('🛒 Catálogo de productos en inventario:')\n",
    "for item in catalogo_datos:\n",
    "    print(f\" - [{item['id']}] {item['nombre']} | Precio: {formatear_moneda(item['precio'])} | Stock: {item['stock']} uds\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 🛡️ MÓDULO 4: POO - Encapsulamiento\n",
    "\n",
    "El **encapsulamiento** consiste en ocultar o proteger el estado interno de un objeto para evitar modificaciones no autorizadas o inválidas.\n",
    "\n",
    "- Los atributos privados se definen con doble guion bajo (`__precio`, `__stock`).\n",
    "- Usamos los decoradores `@property` (getter) y `@atributo.setter` (setter) para validar los cambios."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class Producto:\n",
    "    \"\"\"\n",
    "    Clase Base que representa un producto del inventario.\n",
    "    Aplica Encapsulamiento en precio y stock.\n",
    "    \"\"\"\n",
    "    def __init__(self, codigo, nombre, precio_base, stock):\n",
    "        self.codigo = codigo                # Atributo público\n",
    "        self.nombre = nombre                # Atributo público\n",
    "        self.__precio_base = 0.0            # Atributo privado\n",
    "        self.__stock = 0                    # Atributo privado\n",
    "        \n",
    "        # Usamos los setters para asignar valores con validación previa\n",
    "        self.precio_base = precio_base\n",
    "        self.stock = stock\n",
    "\n",
    "    # --- ENCAPSULAMIENTO: Getter y Setter de PRECIO --- \n",
    "    @property\n",
    "    def precio_base(self):\n",
    "        return self.__precio_base\n",
    "\n",
    "    @precio_base.setter\n",
    "    def precio_base(self, valor):\n",
    "        if valor < 0:\n",
    "            raise ValueError('El precio no puede ser un número negativo.')\n",
    "        self.__precio_base = valor\n",
    "\n",
    "    # --- ENCAPSULAMIENTO: Getter y Setter de STOCK --- \n",
    "    @property\n",
    "    def stock(self):\n",
    "        return self.__stock\n",
    "\n",
    "    @stock.setter\n",
    "    def stock(self, cantidad):\n",
    "        if cantidad < 0:\n",
    "            raise ValueError('El stock no puede ser negativo.')\n",
    "        self.__stock = cantidad\n",
    "\n",
    "    # Método general de información\n",
    "    def obtener_resumen(self):\n",
    "        return f\"[{self.codigo}] {self.nombre} - Precio Base: {formatear_moneda(self.precio_base)} | Stock: {self.stock}\"\n",
    "\n",
    "    # Método que será sobrescrito (Polimorfismo)\n",
    "    def calcular_precio_final(self):\n",
    "        # Añade el IVA base al precio\n",
    "        return self.precio_base * 1.13\n",
    "\n",
    "# Probar la clase base\n",
    "prod_test = Producto('PROD-001', 'Mouse Óptico', 25.0, 10)\n",
    "print(prod_test.obtener_resumen())\n",
    "print(f\"Precio Final con IVA: {formatear_moneda(prod_test.calcular_precio_final())}\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 🧬 MÓDULO 5: POO - Herencia y Polimorfismo\n",
    "\n",
    "- **Herencia**: Las clases Hijas (`ProductoElectronico` y `ProductoAlimento`) heredan los atributos y métodos de la clase Padre (`Producto`).\n",
    "- **Polimorfismo**: Cada clase Hija redefine el método `calcular_precio_final()` y `obtener_resumen()` a su propia manera."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. CLASE HIJA 1: ProductoElectrónico (Hereda de Producto)\n",
    "class ProductoElectronico(Producto):\n",
    "    def __init__(self, codigo, nombre, precio_base, stock, garantia_meses=12):\n",
    "        # Llamamos al constructor de la clase Padre\n",
    "        super().__init__(codigo, nombre, precio_base, stock)\n",
    "        self.garantia_meses = garantia_meses\n",
    "\n",
    "    # POLIMORFISMO: Redefinición de calcular_precio_final (Agrega tasa de garantía extendida)\n",
    "    def calcular_precio_final(self):\n",
    "        precio_con_iva = super().calcular_precio_final()\n",
    "        # Si tiene más de 12 meses de garantía, se cobra $15 adicionales por seguro\n",
    "        costo_garantia = 15.0 if self.garantia_meses > 12 else 0.0\n",
    "        return precio_con_iva + costo_garantia\n",
    "\n",
    "    # POLIMORFISMO: Redefinición de obtener_resumen\n",
    "    def obtener_resumen(self):\n",
    "        resumen_padre = super().obtener_resumen()\n",
    "        return f\"{resumen_padre} | Garantía: {self.garantia_meses} meses (Electrónico)\"\n",
    "\n",
    "# 2. CLASE HIJA 2: ProductoAlimento (Hereda de Producto)\n",
    "class ProductoAlimento(Producto):\n",
    "    def __init__(self, codigo, nombre, precio_base, stock, dias_para_vencer):\n",
    "        super().__init__(codigo, nombre, precio_base, stock)\n",
    "        self.dias_para_vencer = dias_para_vencer\n",
    "\n",
    "    # POLIMORFISMO: Redefinición de calcular_precio_final (Aplica liquidación si vence pronto)\n",
    "    def calcular_precio_final(self):\n",
    "        precio_con_iva = super().calcular_precio_final()\n",
    "        # Si le quedan 3 días o menos para vencer, recibe 40% de descuento automático\n",
    "        if self.dias_para_vencer <= 3:\n",
    "            print(f\"⚠️ ¡ALERTA LIQUIDACIÓN! {self.nombre} vence en {self.dias_para_vencer} días (40% OFF).\")\n",
    "            return precio_con_iva * 0.60\n",
    "        return precio_con_iva\n",
    "\n",
    "    # POLIMORFISMO: Redefinición de obtener_resumen\n",
    "    def obtener_resumen(self):\n",
    "        resumen_padre = super().obtener_resumen()\n",
    "        return f\"{resumen_padre} | Vence en: {self.dias_para_vencer} días (Alimento)\"\n",
    "\n",
    "# --- DEMOSTRACIÓN DE POLIMORFISMO ---\n",
    "# Creamos una lista heterogénea de productos (Objetos de distintas clases)\n",
    "lista_productos = [\n",
    "    ProductoElectronico('ELEC-101', 'Monitor 27 FPS', 300.0, 8, garantia_meses=24),\n",
    "    ProductoAlimento('ALIM-202', 'Café de Grano 1Kg', 15.0, 20, dias_para_vencer=2),\n",
    "    ProductoElectronico('ELEC-103', 'Teclado Mecánico', 60.0, 12, garantia_meses=12)\n",
    "]\n",
    "\n",
    "print('✨ DEMOSTRACIÓN DE POLIMORFISMO (Un mismo método calcular_precio_final() responde distinto):')\n",
    "print('-' * 85)\n",
    "for p in lista_productos:\n",
    "    print(p.obtener_resumen())\n",
    "    print(f\"👉 Precio Final Calculado: {formatear_moneda(p.calcular_precio_final())}\\n\")\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## ⚠️ MÓDULO 6: Manejo de Excepciones y Excepciones Personalizadas\n",
    "\n",
    "El manejo de excepciones permite capturar errores de ejecución para evitar que el programa colapse inesperadamente."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Definimos nuestra propia Excepción Personalizada\n",
    "class StockInsuficienteError(Exception):\n",
    "    \"\"\"Excepción lanzada cuando se intenta vender más stock del disponible.\"\"\"\n",
    "    def __init__(self, solicitado, disponible):\n",
    "        super().__init__(f\"Stock insuficiente: Solicitado {solicitado}, pero solo hay {disponible} unidades disponibles.\")\n",
    "        self.solicitado = solicitado\n",
    "        self.disponible = disponible\n",
    "\n",
    "# 2. Función para realizar una venta con captura de errores\n",
    "def procesar_venta(producto, cantidad_deseada):\n",
    "    print(f\"\\n🛒 Intentando comprar {cantidad_deseada} unidades de '{producto.nombre}'...\")\n",
    "    \n",
    "    try:\n",
    "        # Validar tipo de dato de entrada\n",
    "        if not isinstance(cantidad_deseada, int) or cantidad_deseada <= 0:\n",
    "            raise TypeError('La cantidad comprada debe ser un número entero positivo mayores a cero.')\n",
    "            \n",
    "        # Validar disponibilidad de stock\n",
    "        if cantidad_deseada > producto.stock:\n",
    "            raise StockInsuficienteError(cantidad_deseada, producto.stock)\n",
    "            \n",
    "        # Si todo es correcto, descontar stock\n",
    "        producto.stock -= cantidad_deseada\n",
    "        total_pagar = producto.calcular_precio_final() * cantidad_deseada\n",
    "        print(f\"✅ Venta exitosa. Total cobrado: {formatear_moneda(total_pagar)}\")\n",
    "        print(f\"📦 Stock restante de '{producto.nombre}': {producto.stock} unidades.\")\n",
    "        \n",
    "    except StockInsuficienteError as error_stock:\n",
    "        print(f\"❌ ERROR DE STOCK: {error_stock}\")\n",
    "        \n",
    "    except TypeError as error_tipo:\n",
    "        print(f\"❌ ERROR DE DATO: {error_tipo}\")\n",
    "        \n",
    "    except Exception as error_general:\n",
    "        print(f\"❌ ERROR INESPERADO: {error_general}\")\n",
    "        \n",
    "    finally:\n",
    "        print(\"🔹 (Bloque 'finally': Operación finalizada e historial de auditoría actualizado).\")\n",
    "\n",
    "# --- PRUEBAS DE EXCEPCIONES ---\n",
    "laptop = ProductoElectronico('LAP-001', 'Laptop HP Pro', 800.0, 3)\n",
    "\n",
    "# Prueba 1: Venta exitosa\n",
    "procesar_venta(laptop, 2)\n",
    "\n",
    "# Prueba 2: Excepción por Stock Insuficiente (Queda 1 en stock, solicitamos 5)\n",
    "procesar_venta(laptop, 5)\n",
    "\n",
    "# Prueba 3: Excepción por tipo de dato inválido\n",
    "procesar_venta(laptop, -2)\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 🏆 MÓDULO 7: Integración Total del Mini-Proyecto\n",
    "\n",
    "A continuación, integramos todos los conceptos aprendidos en un gestor de inventario completo."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "class GestorInventario:\n",
    "    \"\"\"\n",
    "    Clase Gestora que almacena los productos en una lista y diccionario,\n",
    "    demostrando la interacción de todos los conceptos requeridos.\n",
    "    \"\"\"\n",
    "    def __init__(self, nombre_tienda):\n",
    "        self.nombre_tienda = nombre_tienda\n",
    "        self.inventario_lista = []       # Lista de objetos Producto\n",
    "        self.inventario_dict = {}        # Diccionario con clave = código de producto\n",
    "\n",
    "    def agregar_producto(self, producto):\n",
    "        if not isinstance(producto, Producto):\n",
    "            raise TypeError('Solo se pueden agregar objetos que deriven de la clase Producto.')\n",
    "        self.inventario_lista.append(producto)\n",
    "        self.inventario_dict[producto.codigo] = producto\n",
    "        print(f\"➕ Producto registrado: [{producto.codigo}] {producto.nombre}\")\n",
    "\n",
    "    def buscar_por_codigo(self, codigo):\n",
    "        try:\n",
    "            return self.inventario_dict[codigo]\n",
    "        except KeyError:\n",
    "            print(f\"⚠️ Error: El producto con código '{codigo}' no existe en la tienda.\")\n",
    "            return None\n",
    "\n",
    "    def mostrar_reporte_completo(self):\n",
    "        mostrar_banner()\n",
    "        print(f\"📍 REPORTE GENERAL DE INVENTARIO | {mi.obtener_timestamp()}\")\n",
    "        print('-' * 85)\n",
    "        \n",
    "        total_valor_inventario = 0.0\n",
    "        for prod in self.inventario_lista:\n",
    "            # Polimorfismo en acción al llamar a obtener_resumen() y calcular_precio_final()\n",
    "            print(prod.obtener_resumen())\n",
    "            precio_f = prod.calcular_precio_final()\n",
    "            valor_subtotal = precio_f * prod.stock\n",
    "            total_valor_inventario += valor_subtotal\n",
    "            print(f\"   💰 Precio Final c/Impuesto: {formatear_moneda(precio_f)} | Valor Total Stock: {formatear_moneda(valor_subtotal)}\\n\")\n",
    "            \n",
    "        print('=' * 85)\n",
    "        print(f\"💵 VALOR TOTAL DEL INVENTARIO EN TIENDA: {formatear_moneda(total_valor_inventario)}\")\n",
    "        print('=' * 85)\n",
    "\n",
    "# === EJECUCIÓN FINAL DE INTEGRACIÓN ===\n",
    "mi_tienda = GestorInventario('TechStore Costa Rica')\n",
    "\n",
    "# Creación de Productos usando Módulo Custom para generar código\n",
    "prod1 = ProductoElectronico(generar_codigo_unico('TV'), 'Smart TV 55 Pulgadas', 550.0, 4, garantia_meses=24)\n",
    "prod2 = ProductoAlimento(generar_codigo_unico('SNK'), 'Chocolates Gourmet', 8.50, 30, dias_para_vencer=1)\n",
    "prod3 = ProductoElectronico(generar_codigo_unico('AUD'), 'Audífonos Noise Cancelling', 120.0, 10, garantia_meses=12)\n",
    "\n",
    "# Agregar productos al gestor\n",
    "mi_tienda.agregar_producto(prod1)\n",
    "mi_tienda.agregar_producto(prod2)\n",
    "mi_tienda.agregar_producto(prod3)\n",
    "\n",
    "# Mostrar Reporte Completo\n",
    "mi_tienda.mostrar_reporte_completo()\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 🎓 Resumen de Aprendizaje del Proyecto\n",
    "\n",
    "¡Felicidades! Has completado la estructura de tu Mini-Proyecto. Revisa la tabla de correspondencia:\n",
    "\n",
    "| Requisito del Curso | ¿Dónde se implementó en el proyecto? |\n",
    "| :--- | :--- |\n",
    "| **Módulos** | Archivo `modulo_inventario.py` e imports (`import datetime`, `from modulo... import ...`) |\n",
    "| **Listas** | `categorias`, `catalogo_datos`, `self.inventario_lista` |\n",
    "| **Diccionarios** | `tienda_info`, `catalogo_datos`, `self.inventario_dict` |\n",
    "| **Funciones s/parámetro** | `mostrar_banner()`, `obtener_timestamp()` |\n",
    "| **Funciones c/parámetro** | `calcular_descuento(precio_base, porcentaje_descuento=10)` |\n",
    "| **Encapsulamiento** | Atributos privados `__precio_base` y `__stock` con decoradores `@property` |\n",
    "| **Herencia** | Clases `ProductoElectronico` y `ProductoAlimento` heredan de `Producto` |\n",
    "| **Polimorfismo** | Métodos `calcular_precio_final()` y `obtener_resumen()` redefinidos en cada subclase |\n",
    "| **Excepciones** | Bloques `try/except/finally` y excepción personalizada `StockInsuficienteError` |"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

output_path = r"C:\Users\Carlos.Arauz\.gemini\antigravity\scratch\mini_proyecto_python\mini_proyecto_python.ipynb"

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(notebook_content, f, indent=1, ensure_ascii=False)

print("SUCCESSFULLY GENERATED VALID JSON NOTEBOOK AT:", output_path)
